//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QSMgmtEntities : DbContext
    {
        public QSMgmtEntities()
            : base("name=QSMgmtEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Approval> Approvals { get; set; }
        public virtual DbSet<BacklogItem> BacklogItems { get; set; }
        public virtual DbSet<ChangeType> ChangeTypes { get; set; }
        public virtual DbSet<Impact> Impacts { get; set; }
        public virtual DbSet<Priority> Priorities { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Sprint> Sprints { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<TaskState> TaskStates { get; set; }
        public virtual DbSet<TaskUpdate> TaskUpdates { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<TestOutcome> TestOutcomes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VersionOrigin> VersionOrigins { get; set; }
    }
}
