//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Priority
    {
        public Priority()
        {
            this.ChangeRequests = new HashSet<ChangeRequest>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Erased { get; set; }
    
        public virtual ICollection<ChangeRequest> ChangeRequests { get; set; }
    }
}
