//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.BacklogItems = new HashSet<BacklogItem>();
            this.Sprints = new HashSet<Sprint>();
            this.Teams = new HashSet<Team>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool Erased { get; set; }
    
        public virtual ICollection<BacklogItem> BacklogItems { get; set; }
        public virtual ICollection<Sprint> Sprints { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
    }
}
