//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.TaskUpdates = new HashSet<TaskUpdate>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool Erased { get; set; }
        public int RemainingTime { get; set; }
        public int TaskStateId { get; set; }
        public Nullable<int> SprintId { get; set; }
        public int BacklogItemId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual BacklogItem BacklogItem { get; set; }
        public virtual Sprint Sprint { get; set; }
        public virtual TaskState TaskState { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<TaskUpdate> TaskUpdates { get; set; }
    }
}
