//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskUpdate
    {
        public int Id { get; set; }
        public string Comment { get; set; }
        public System.DateTime EventDate { get; set; }
        public bool Erased { get; set; }
        public int ElapsedTime { get; set; }
        public Nullable<int> TaskId { get; set; }
        public int PreviousTaskStateId { get; set; }
        public int TaskStateId { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual TaskState TaskState { get; set; }
        public virtual TaskState TaskState1 { get; set; }
    }
}
