//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test : BacklogItem
    {
        public string Steps { get; set; }
        public int VersionOriginId { get; set; }
        public int TestOutcomeId { get; set; }
    
        public virtual TestOutcome TestOutcome { get; set; }
        public virtual VersionOrigin VersionOrigin { get; set; }
    }
}
